### ISSUE TITLE
Date Picker: No initial value shown, even if set.

### ISSUE THREAD

**Issue by clintonmyers** [aavanzyl/ngx-tiny#13]
Hello, I'm not sure if this is a bug or feature request, but I noticed (after jumping into development), that the examples in the docs do not display the initial date value inside the <input> tag that was set in the TypeScript (looking at the single date example for instance). I am doing reactive forms where initial or asynchronous values will need to be set programmatically and displayed, and not all values will be set with the datepicker itself. Is this intentionally set up this way with this functionality unwanted, or perhaps I've made a mistake and this functionality is currently possible (user error). I am able to use the date picker successfully with my form otherwise for dates that I set manually. Thanks!

https://aavanzyl.github.io/ngx-tiny/project/date-picker
Usage tab

**Comment by aavanzyl** [comment]
@clintonmyers This looks like a bug, I will need to correct this and revert back to you, wont take too long :) 

The expected behavior is when setting/changing a date, the display is update. It is updating when setting a new date from the UI, but not from the controller. Will sort this out for you asap

**Comment by clintonmyers** [comment]
Thanks so much for the quick response!

**Comment by aavanzyl** [comment]
@clintonmyers I have made the fix and published v10.0.1, please test and let me know if its working on your side as well.

**Comment by clintonmyers** [comment]
@aavanzyl Yes, that fixed the issue. Thanks!

**Comment by clintonmyers** [comment]
Actually, another note about this, the date picker isn't picking up my DatePickerOptions for my displayFormat on the initial load, only when I set it manually.

**Comment by clintonmyers** [comment]
@aavanzyl, wondering if you had a chance to look into this yet? Thanks, again. Clint

**Comment by aavanzyl** [comment]
@clintonmyers I have deployed version 10.2 to fix the issue you are referring to. Please test and let me know.

**Comment by clintonmyers** [comment]
Thank you for the help @aavanzyl . Another developer on my team was able to use a short setTimeout to bypass the issue. I will remove the setTimeout and report back.

**Comment by clintonmyers** [comment]
@aavanzyl The other developer told me that the update did not solve the problem when he removed the setTimeout. I'm going to continue to use the setTimeout for now. Thanks.

**Comment by mishelka** [comment]
I have the same issue, but the value does not display at all when changing externally. I'm using the same example as the last one in the demo, initial value is always set to ```today``` and when I'm using two inline calendars with the same value, the other one does not update the view despite the source value is being updated.
